<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\Yaml\Yaml;

/**
 * Implements hook_form_alter().
 */
function migration_glue_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'migration_admin_form') {
    $form['output']['#tree'] = TRUE;
    $default_option_label = $form['migration_group']['#options']['default'];
    $form['migration_group']['#options'] = ['default' => $default_option_label];
    $form['migration_group']['#default_value'] = 'default';
    $form['next_step'] = [
      '#type' => 'submit',
      '#value' => t('Go to next step'),
      '#submit' => ['_migration_glue_submit_handler'],
    ];
  }
}

/**
 * Submit handler.
 */
function _migration_glue_submit_handler(array &$form, FormStateInterface $form_state) {
  // Get exported output.
  $output = $form_state->getValue('output')['export'];
  $source = $form_state->getValue('data_source_config_wrapper')['source'];

  // Item selector must have a trailing slash as we are replacing it with empty
  // string. If no tailing slash, then we adding it here.
  $item_selector = substr($source['json_item_selector'], -1) == '/' ? $source['json_item_selector'] : $source['json_item_selector'] . '/';

  // We are removing item selector from the source and process part of the
  // migration output otherwise migration throws error -
  // "Migration failed with source plugin exception: /pages/page/id is defined
  // as a source ID but has no value".
  $output = str_replace($item_selector, '', $output);

  // Parsed yml to array.
  $parsed_yml = Yaml::parse($output);

  // @Todo - Need to make it more generic (like for CSV).
  $parsed_yml['source']['data_fetcher_plugin'] = 'http';
  $parsed_yml['source']['urls'] = $source['json_path'];
  $parsed_yml['source']['item_selector'] = $source['json_item_selector'];

  // Register the migration in system.
  _migration_glue_register_migration($parsed_yml);

  // Adding status message.
  \Drupal::messenger()->addStatus(t('Migration @migration has been created successfully.', ['@migration' => $parsed_yml['id']]));

  // Redirect to next step.
  $form_state->setRedirect('migration_glue.run_migration', [
    'migration' => $parsed_yml['id'],
    'migration_group' => $parsed_yml['migration_group'],
  ]);
}

/**
 * Register a migration to the system.
 *
 * @param array $yml_data
 *   YML content.
 */
function _migration_glue_register_migration(array $yml_data = []) {
  if (!empty($yml_data)) {
    $migration_name = 'migrate_plus.migration.' . $yml_data['id'];
    \Drupal::configFactory()->getEditable($migration_name)->setData($yml_data)->save();
  }
}
