<?php

/**
 * Implements hook_uninstall().
 *
 * Cleans up config entities installed by this module.
 */
function xml_migrate_uninstall() {
  db_query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.user_xml_migrate%'");
  db_query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.tags_xml_migrate%'");
  db_query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.content_xml_migrate%'");
  db_query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.comment_xml_migrate%'");
  drupal_flush_all_caches();
}
