<?php

/**
 * @file
 * Contains migration_mapper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migration_mapper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migration_mapper module.
    case 'help.page.migration_mapper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maps data files to Migration yml.') . '</p>';
      return $output;

    default:
  }
}
